// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVyuzQF3lyyKAPuInAtIlVqIwuIDDoU4',
    appId: '1:321873723616:android:2935467dd0279da0055085',
    messagingSenderId: '321873723616',
    projectId: 'medical3d-c5222',
    storageBucket: 'medical3d-c5222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsi-oU1bTctRNTwp4mf6GaDs8_SYKURpY',
    appId: '1:321873723616:ios:5ff1b3a7724418e9055085',
    messagingSenderId: '321873723616',
    projectId: 'medical3d-c5222',
    storageBucket: 'medical3d-c5222.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsi-oU1bTctRNTwp4mf6GaDs8_SYKURpY',
    appId: '1:321873723616:ios:5ff1b3a7724418e9055085',
    messagingSenderId: '321873723616',
    projectId: 'medical3d-c5222',
    storageBucket: 'medical3d-c5222.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1vazmWShesUZAv61aSi0rThrwVP0ejGE',
    appId: '1:321873723616:web:73ace213508659ef055085',
    messagingSenderId: '321873723616',
    projectId: 'medical3d-c5222',
    authDomain: 'medical3d-c5222.firebaseapp.com',
    storageBucket: 'medical3d-c5222.appspot.com',
    measurementId: 'G-JK4JTJFQR5',
  );
}
